/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  SADocument,
  SADocumentDescription,
  SAMediaInfo,
  SAMediaSearchRequest
} from './model';

interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class SchulaufgabenEditorWebV1Service {
  private readonly http = inject(HttpClient);
 getAPIDocumentDescription<TData = SADocumentDescription[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getAPIDocumentDescription<TData = SADocumentDescription[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getAPIDocumentDescription<TData = SADocumentDescription[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getAPIDocumentDescription<TData = SADocumentDescription[]>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/API/DocumentDescription`,options
    );
  }

 putAPIDocumentDescription<TData = SADocumentDescription>(sADocumentDescription: SADocumentDescription, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 putAPIDocumentDescription<TData = SADocumentDescription>(sADocumentDescription: SADocumentDescription, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 putAPIDocumentDescription<TData = SADocumentDescription>(sADocumentDescription: SADocumentDescription, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  putAPIDocumentDescription<TData = SADocumentDescription>(
    sADocumentDescription: SADocumentDescription, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.put<TData>(
      `/API/DocumentDescription`,
      sADocumentDescription,options
    );
  }

 getAPIDocumentDescriptionId<TData = SADocumentDescription>(id: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getAPIDocumentDescriptionId<TData = SADocumentDescription>(id: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getAPIDocumentDescriptionId<TData = SADocumentDescription>(id: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getAPIDocumentDescriptionId<TData = SADocumentDescription>(
    id: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/API/DocumentDescription/${id}`,options
    );
  }

 postAPIDocumentDescriptionId<TData = SADocumentDescription>(id: string,
    sADocumentDescription: SADocumentDescription, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postAPIDocumentDescriptionId<TData = SADocumentDescription>(id: string,
    sADocumentDescription: SADocumentDescription, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postAPIDocumentDescriptionId<TData = SADocumentDescription>(id: string,
    sADocumentDescription: SADocumentDescription, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postAPIDocumentDescriptionId<TData = SADocumentDescription>(
    id: string,
    sADocumentDescription: SADocumentDescription, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/API/DocumentDescription/${id}`,
      sADocumentDescription,options
    );
  }

 deleteAPIDocumentDescriptionId<TData = void>(id: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteAPIDocumentDescriptionId<TData = void>(id: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteAPIDocumentDescriptionId<TData = void>(id: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteAPIDocumentDescriptionId<TData = void>(
    id: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(
      `/API/DocumentDescription/${id}`,options
    );
  }

 getAPIDocumentId<TData = SADocument>(id: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getAPIDocumentId<TData = SADocument>(id: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getAPIDocumentId<TData = SADocument>(id: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getAPIDocumentId<TData = SADocument>(
    id: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/API/Document/${id}`,options
    );
  }

 postAPIDocumentId<TData = SADocument>(id: string,
    sADocument: SADocument, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postAPIDocumentId<TData = SADocument>(id: string,
    sADocument: SADocument, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postAPIDocumentId<TData = SADocument>(id: string,
    sADocument: SADocument, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postAPIDocumentId<TData = SADocument>(
    id: string,
    sADocument: SADocument, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/API/Document/${id}`,
      sADocument,options
    );
  }

 deleteAPIDocumentId<TData = void>(id: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 deleteAPIDocumentId<TData = void>(id: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 deleteAPIDocumentId<TData = void>(id: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  deleteAPIDocumentId<TData = void>(
    id: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.delete<TData>(
      `/API/Document/${id}`,options
    );
  }

 putAPIDocument<TData = SADocument>(sADocument: SADocument, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 putAPIDocument<TData = SADocument>(sADocument: SADocument, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 putAPIDocument<TData = SADocument>(sADocument: SADocument, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  putAPIDocument<TData = SADocument>(
    sADocument: SADocument, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.put<TData>(
      `/API/Document`,
      sADocument,options
    );
  }

 getAPIMediaContentName<TData = void>(name: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getAPIMediaContentName<TData = void>(name: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getAPIMediaContentName<TData = void>(name: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getAPIMediaContentName<TData = void>(
    name: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/API/Media/Content/${name}`,options
    );
  }

 getAPIMediaThumbnailName<TData = void>(name: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getAPIMediaThumbnailName<TData = void>(name: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getAPIMediaThumbnailName<TData = void>(name: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getAPIMediaThumbnailName<TData = void>(
    name: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/API/Media/Thumbnail/${name}`,options
    );
  }

 postAPIMediaSearch<TData = SAMediaInfo[]>(sAMediaSearchRequest: SAMediaSearchRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postAPIMediaSearch<TData = SAMediaInfo[]>(sAMediaSearchRequest: SAMediaSearchRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postAPIMediaSearch<TData = SAMediaInfo[]>(sAMediaSearchRequest: SAMediaSearchRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postAPIMediaSearch<TData = SAMediaInfo[]>(
    sAMediaSearchRequest: SAMediaSearchRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/API/Media/Search`,
      sAMediaSearchRequest,options
    );
  }

};

export type GetAPIDocumentDescriptionClientResult = NonNullable<SADocumentDescription[]>
export type PutAPIDocumentDescriptionClientResult = NonNullable<SADocumentDescription>
export type GetAPIDocumentDescriptionIdClientResult = NonNullable<SADocumentDescription>
export type PostAPIDocumentDescriptionIdClientResult = NonNullable<SADocumentDescription>
export type DeleteAPIDocumentDescriptionIdClientResult = NonNullable<void>
export type GetAPIDocumentIdClientResult = NonNullable<SADocument>
export type PostAPIDocumentIdClientResult = NonNullable<SADocument>
export type DeleteAPIDocumentIdClientResult = NonNullable<void>
export type PutAPIDocumentClientResult = NonNullable<SADocument>
export type GetAPIMediaContentNameClientResult = NonNullable<void>
export type GetAPIMediaThumbnailNameClientResult = NonNullable<void>
export type PostAPIMediaSearchClientResult = NonNullable<SAMediaInfo[]>
