/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */

export * from './sadocument-description-sa-document-description-type';
export * from './sadocument-description-sa-document-description';
export * from './sadocument-description';