/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SABoxLeft } from './SABoxLeft';
import type { SABoxTop } from './SABoxTop';
import type { SABoxWidth } from './SABoxWidth';
import type { SABoxHeight } from './SABoxHeight';
import type { SABoxRight } from './SABoxRight';
import type { SABoxBottom } from './SABoxBottom';

export interface SABox {
  Left?: SABoxLeft;
  Top?: SABoxTop;
  Width?: SABoxWidth;
  Height?: SABoxHeight;
  Right?: SABoxRight;
  Bottom?: SABoxBottom;
}
