/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SABorderSABorderType } from './saborder-sa-border-type';
import type { SABorderSABorderBorderWidth } from './saborder-sa-border-border-width';
import type { SABorderSABorderBorderTopWidth } from './saborder-sa-border-border-top-width';
import type { SABorderSABorderBorderRightWidth } from './saborder-sa-border-border-right-width';
import type { SABorderSABorderBorderBottomWidth } from './saborder-sa-border-border-bottom-width';
import type { SABorderSABorderBorderLeftWidth } from './saborder-sa-border-border-left-width';
import type { SABorderSABorderBorderStyle } from './saborder-sa-border-border-style';
import type { SABorderSABorderBorderTopStyle } from './saborder-sa-border-border-top-style';
import type { SABorderSABorderBorderRightStyle } from './saborder-sa-border-border-right-style';
import type { SABorderSABorderBorderBottomStyle } from './saborder-sa-border-border-bottom-style';
import type { SABorderSABorderBorderLeftStyle } from './saborder-sa-border-border-left-style';
import type { SABorderSABorderBorderColor } from './saborder-sa-border-border-color';
import type { SABorderSABorderBorderTopColor } from './saborder-sa-border-border-top-color';
import type { SABorderSABorderBorderRightColor } from './saborder-sa-border-border-right-color';
import type { SABorderSABorderBorderBottomColor } from './saborder-sa-border-border-bottom-color';
import type { SABorderSABorderBorderLeftColor } from './saborder-sa-border-border-left-color';
import type { SABorderSABorderBorderRadius } from './saborder-sa-border-border-radius';
import type { SABorderSABorderBorderTopLeftRadius } from './saborder-sa-border-border-top-left-radius';
import type { SABorderSABorderBorderTopRightRadius } from './saborder-sa-border-border-top-right-radius';
import type { SABorderSABorderBorderBottomRightRadius } from './saborder-sa-border-border-bottom-right-radius';
import type { SABorderSABorderBorderBottomLeftRadius } from './saborder-sa-border-border-bottom-left-radius';

export interface SABorderSABorder {
  $type: SABorderSABorderType;
  borderWidth?: SABorderSABorderBorderWidth;
  borderTopWidth?: SABorderSABorderBorderTopWidth;
  borderRightWidth?: SABorderSABorderBorderRightWidth;
  borderBottomWidth?: SABorderSABorderBorderBottomWidth;
  borderLeftWidth?: SABorderSABorderBorderLeftWidth;
  borderStyle?: SABorderSABorderBorderStyle;
  borderTopStyle?: SABorderSABorderBorderTopStyle;
  borderRightStyle?: SABorderSABorderBorderRightStyle;
  borderBottomStyle?: SABorderSABorderBorderBottomStyle;
  borderLeftStyle?: SABorderSABorderBorderLeftStyle;
  borderColor?: SABorderSABorderBorderColor;
  borderTopColor?: SABorderSABorderBorderTopColor;
  borderRightColor?: SABorderSABorderBorderRightColor;
  borderBottomColor?: SABorderSABorderBorderBottomColor;
  borderLeftColor?: SABorderSABorderBorderLeftColor;
  borderRadius?: SABorderSABorderBorderRadius;
  borderTopLeftRadius?: SABorderSABorderBorderTopLeftRadius;
  borderTopRightRadius?: SABorderSABorderBorderTopRightRadius;
  borderBottomRightRadius?: SABorderSABorderBorderBottomRightRadius;
  borderBottomLeftRadius?: SABorderSABorderBorderBottomLeftRadius;
}
