/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SABoxSABoxType } from './sabox-sa-box-type';
import type { SABoxSABoxLeft } from './sabox-sa-box-left';
import type { SABoxSABoxTop } from './sabox-sa-box-top';
import type { SABoxSABoxWidth } from './sabox-sa-box-width';
import type { SABoxSABoxHeight } from './sabox-sa-box-height';
import type { SABoxSABoxRight } from './sabox-sa-box-right';
import type { SABoxSABoxBottom } from './sabox-sa-box-bottom';

export interface SABoxSABox {
  $type: SABoxSABoxType;
  left?: SABoxSABoxLeft;
  top?: SABoxSABoxTop;
  width?: SABoxSABoxWidth;
  height?: SABoxSABoxHeight;
  right?: SABoxSABoxRight;
  bottom?: SABoxSABoxBottom;
}
