/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SAContentSAContentType } from './sacontent-sa-content-type';
import type { SAContentSAContentMatchingValue } from './sacontent-sa-content-matching-value';
import type { SAContentSAContentBackground } from './sacontent-sa-content-background';
import type { SAContentSAContentBorder } from './sacontent-sa-content-border';
import type { SAContentSAContentText } from './sacontent-sa-content-text';
import type { SAContentSAContentImage } from './sacontent-sa-content-image';
import type { SAContentSAContentAudio } from './sacontent-sa-content-audio';
import type { SAContentSAContentVideo } from './sacontent-sa-content-video';

export interface SAContentSAContent {
  $type: SAContentSAContentType;
  matchingValue?: SAContentSAContentMatchingValue;
  background?: SAContentSAContentBackground;
  border?: SAContentSAContentBorder;
  text?: SAContentSAContentText;
  image?: SAContentSAContentImage;
  audio?: SAContentSAContentAudio;
  video?: SAContentSAContentVideo;
}
