/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SAContentMatchingValue } from './SAContentMatchingValue';
import type { SAContentBackground } from './SAContentBackground';
import type { SAContentBorder } from './SAContentBorder';
import type { SAContentText } from './SAContentText';
import type { SAContentImage } from './SAContentImage';
import type { SAContentAudio } from './SAContentAudio';
import type { SAContentVideo } from './SAContentVideo';

export interface SAContent {
  MatchingValue?: SAContentMatchingValue;
  Background?: SAContentBackground;
  Border?: SAContentBorder;
  Text?: SAContentText;
  Image?: SAContentImage;
  Audio?: SAContentAudio;
  Video?: SAContentVideo;
}
