/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SAColorValue } from './SAColorValue';
import type { SAColorName } from './SAColorName';

export interface SAColor {
  Value?: SAColorValue;
  Name?: SAColorName;
}
