/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SAColorSAColorType } from './sacolor-sa-color-type';
import type { SAColorSAColorValue } from './sacolor-sa-color-value';
import type { SAColorSAColorName } from './sacolor-sa-color-name';

export interface SAColorSAColor {
  $type: SAColorSAColorType;
  value?: SAColorSAColorValue;
  name?: SAColorSAColorName;
}
