/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SAContentMatchingValue } from './sacontent-matching-value';
import type { SAContentText } from './sacontent-text';
import type { SAContentImage } from './sacontent-image';
import type { SAContentAudio } from './sacontent-audio';
import type { SAContentVideo } from './sacontent-video';

export interface SAContent {
  matchingValue?: SAContentMatchingValue;
  text?: SAContentText;
  image?: SAContentImage;
  audio?: SAContentAudio;
  video?: SAContentVideo;
}
