/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SADocumentSADocumentType } from './sadocument-sa-document-type';
import type { SAMedia } from './samedia';
import type { SADocumentSADocumentDecoration } from './sadocument-sa-document-decoration';
import type { SADocumentSADocumentInteraction } from './sadocument-sa-document-interaction';

export interface SADocumentSADocument {
  $type: SADocumentSADocumentType;
  id?: string;
  name?: string;
  description?: string;
  kindInteraction?: string;
  listMedia?: SAMedia[];
  decoration?: SADocumentSADocumentDecoration;
  interaction?: SADocumentSADocumentInteraction;
}
