/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SADocumentDescriptionSADocumentDescriptionType } from './sadocument-description-sa-document-description-type';

export interface SADocumentDescriptionSADocumentDescription {
  $type: SADocumentDescriptionSADocumentDescriptionType;
  id?: string;
  folder?: string;
  name?: string;
  description?: string;
  contentHash?: string;
}
