/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SADocumentSADocumentType } from './sadocument-sa-document-type';
import type { SAMedia } from './samedia';
import type { SADocumentSADocumentDecoration } from './sadocument-sa-document-decoration';
import type { SADocumentSADocumentInteraction } from './sadocument-sa-document-interaction';
import type { SADocumentSADocumentWidth } from './sadocument-sa-document-width';
import type { SADocumentSADocumentHeight } from './sadocument-sa-document-height';
import type { SADocumentSADocumentDefinedHorizontal } from './sadocument-sa-document-defined-horizontal';
import type { SADocumentSADocumentDefinedVertical } from './sadocument-sa-document-defined-vertical';
import type { SADocumentSADocumentDefinedColor } from './sadocument-sa-document-defined-color';
import type { SADocumentSADocumentRulerHorizontal } from './sadocument-sa-document-ruler-horizontal';
import type { SADocumentSADocumentRulerVertical } from './sadocument-sa-document-ruler-vertical';

export interface SADocumentSADocument {
  $type: SADocumentSADocumentType;
  id?: string;
  name?: string;
  description?: string;
  kindInteraction?: string;
  listMedia?: SAMedia[];
  decoration?: SADocumentSADocumentDecoration;
  interaction?: SADocumentSADocumentInteraction;
  width?: SADocumentSADocumentWidth;
  height?: SADocumentSADocumentHeight;
  definedHorizontal?: SADocumentSADocumentDefinedHorizontal;
  definedVertical?: SADocumentSADocumentDefinedVertical;
  definedColor?: SADocumentSADocumentDefinedColor;
  rulerHorizontal?: SADocumentSADocumentRulerHorizontal;
  rulerVertical?: SADocumentSADocumentRulerVertical;
}
