/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SAExpressionNodeFunctionName } from './SAExpressionNodeFunctionName';
import type { SAExpressionNodeReferenceType } from './SAExpressionNodeReferenceType';
import type { SAExpressionNodeReferenceId } from './SAExpressionNodeReferenceId';
import type { SAExpressionNodeValueText } from './SAExpressionNodeValueText';
import type { SAExpressionNodeListArgument } from './SAExpressionNodeListArgument';

export interface SAExpressionNode {
  FunctionName?: SAExpressionNodeFunctionName;
  ReferenceType?: SAExpressionNodeReferenceType;
  ReferenceId?: SAExpressionNodeReferenceId;
  ValueText?: SAExpressionNodeValueText;
  ListArgument?: SAExpressionNodeListArgument;
}
