/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SAMediaInfoSAMediaInfoType } from './samedia-info-sa-media-info-type';
import type { SAMediaInfoSAMediaInfoSize } from './samedia-info-sa-media-info-size';

export interface SAMediaInfoSAMediaInfo {
  $type: SAMediaInfoSAMediaInfoType;
  path?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  size?: SAMediaInfoSAMediaInfoSize;
}
