/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SANodeSANodeType } from './sanode-sa-node-type';
import type { SANodeSANodeName } from './sanode-sa-node-name';
import type { SANodeSANodeKind } from './sanode-sa-node-kind';
import type { SANodeSANode as SrcFrontend__SANodeSANode } from './sanode-sa-node';
import type { SANodeSANodePosition } from './sanode-sa-node-position';
import type { SANodeSANodeNormal } from './sanode-sa-node-normal';
import type { SANodeSANodeFlipped } from './sanode-sa-node-flipped';
import type { SANodeSANodeSelected } from './sanode-sa-node-selected';

export interface SANodeSANode {
  $type: SANodeSANodeType;
  id: string;
  name?: SANodeSANodeName;
  kind?: SANodeSANodeKind;
  listItem?: SrcFrontend__SANodeSANode;
  position?: SANodeSANodePosition;
  normal?: SANodeSANodeNormal;
  flipped?: SANodeSANodeFlipped;
  selected?: SANodeSANodeSelected;
}
