/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SANodeName } from './SANodeName';
import type { SANodeKind } from './SANodeKind';
import type { SANodePosition } from './SANodePosition';
import type { SANodeNormal } from './SANodeNormal';
import type { SANodeFlipped } from './SANodeFlipped';
import type { SANodeSelected } from './SANodeSelected';

export interface SANode {
  Id: string;
  Name?: SANodeName;
  Kind?: SANodeKind;
  ListItem?: SANode[];
  Position?: SANodePosition;
  Normal?: SANodeNormal;
  Flipped?: SANodeFlipped;
  Selected?: SANodeSelected;
}
