/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SANodeSAGroupType } from './sanode-sa-group-type';
import type { SANodeSAGroupName } from './sanode-sa-group-name';
import type { SANodeSAGroupKind } from './sanode-sa-group-kind';

export interface SANodeSAGroup {
  $type: SANodeSAGroupType;
  listItem?: unknown;
  id: string;
  name?: SANodeSAGroupName;
  kind?: SANodeSAGroupKind;
}
