/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SANodeSAVideoType } from './sanode-sa-video-type';
import type { SANodeSAVideoName } from './sanode-sa-video-name';
import type { SANodeSAVideoKind } from './sanode-sa-video-kind';

export interface SANodeSAVideo {
  $type: SANodeSAVideoType;
  media?: string;
  id: string;
  name?: SANodeSAVideoName;
  kind?: SANodeSAVideoKind;
}
