/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SANodeSATextType } from './sanode-sa-text-type';
import type { SANodeSATextName } from './sanode-sa-text-name';
import type { SANodeSATextKind } from './sanode-sa-text-kind';

export interface SANodeSAText {
  $type: SANodeSATextType;
  value?: string;
  style?: string;
  id: string;
  name?: SANodeSATextName;
  kind?: SANodeSATextKind;
}
