/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */

export type SANodeSAImageType = typeof SANodeSAImageType[keyof typeof SANodeSAImageType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SANodeSAImageType = {
  SAImage: 'SAImage',
} as const;
