/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SANodeSANode } from './sanode-sa-node';
import type { SANodeSAGroup } from './sanode-sa-group';
import type { SANodeSAList } from './sanode-sa-list';
import type { SANodeSAImage } from './sanode-sa-image';
import type { SANodeSAAudio } from './sanode-sa-audio';
import type { SANodeSAVideo } from './sanode-sa-video';
import type { SANodeSAText } from './sanode-sa-text';

export type SANode = SANodeSANode | SANodeSAGroup | SANodeSAList | SANodeSAImage | SANodeSAAudio | SANodeSAVideo | SANodeSAText;
