/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SANodeSAImageType } from './sanode-sa-image-type';
import type { SANodeSAImageName } from './sanode-sa-image-name';
import type { SANodeSAImageKind } from './sanode-sa-image-kind';

export interface SANodeSAImage {
  $type: SANodeSAImageType;
  media?: string;
  id: string;
  name?: SANodeSAImageName;
  kind?: SANodeSAImageKind;
}
