/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SANodeSANodeType } from './sanode-sa-node-type';
import type { SANodeSANodeName } from './sanode-sa-node-name';
import type { SANodeSANodeKind } from './sanode-sa-node-kind';

export interface SANodeSANode {
  $type: SANodeSANodeType;
  id: string;
  name?: SANodeSANodeName;
  kind?: SANodeSANodeKind;
}
