/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SANodeSAListType } from './sanode-sa-list-type';
import type { SANodeSAListName } from './sanode-sa-list-name';
import type { SANodeSAListKind } from './sanode-sa-list-kind';

export interface SANodeSAList {
  $type: SANodeSAListType;
  listItem?: unknown;
  id: string;
  name?: SANodeSAListName;
  kind?: SANodeSAListKind;
}
