/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SANodeSAAudioType } from './sanode-sa-audio-type';
import type { SANodeSAAudioName } from './sanode-sa-audio-name';
import type { SANodeSAAudioKind } from './sanode-sa-audio-kind';

export interface SANodeSAAudio {
  $type: SANodeSAAudioType;
  media?: string;
  id: string;
  name?: SANodeSAAudioName;
  kind?: SANodeSAAudioKind;
}
