/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SAScalarUnitSAScalarUnitType } from './sascalar-unit-sa-scalar-unit-type';
import type { SAScalarUnitSAScalarUnitValue } from './sascalar-unit-sa-scalar-unit-value';
import type { SAUnit } from './saunit';
import type { SAScalarUnitSAScalarUnitName } from './sascalar-unit-sa-scalar-unit-name';

export interface SAScalarUnitSAScalarUnit {
  $type: SAScalarUnitSAScalarUnitType;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  value: SAScalarUnitSAScalarUnitValue;
  unit: SAUnit;
  name?: SAScalarUnitSAScalarUnitName;
}
