/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SAUnit } from './SAUnit';
import type { SAScalarUnitName } from './SAScalarUnitName';

export interface SAScalarUnit {
  Value: number;
  Unit: SAUnit;
  Name?: SAScalarUnitName;
}
