/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SATextSATextType } from './satext-sa-text-type';

export interface SATextSAText {
  $type: SATextSATextType;
  value?: string;
  style?: string;
}
