/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SATextFontFamily } from './SATextFontFamily';
import type { SATextFontSize } from './SATextFontSize';
import type { SATextFontWeight } from './SATextFontWeight';
import type { SATextFontStyle } from './SATextFontStyle';
import type { SATextColor } from './SATextColor';
import type { SATextTextAlign } from './SATextTextAlign';
import type { SATextTextDecoration } from './SATextTextDecoration';

export interface SAText {
  Value?: string;
  FontFamily?: SATextFontFamily;
  FontSize?: SATextFontSize;
  FontWeight?: SATextFontWeight;
  FontStyle?: SATextFontStyle;
  Color?: SATextColor;
  TextAlign?: SATextTextAlign;
  TextDecoration?: SATextTextDecoration;
}
