/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SATransformTransformFunction } from './SATransformTransformFunction';
import type { SATransformListArgument } from './SATransformListArgument';

export interface SATransform {
  Id?: string;
  TransformFunction?: SATransformTransformFunction;
  ListArgument?: SATransformListArgument;
}
