/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * SchulaufgabenEditorWeb | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SAVideoSAVideoType } from './savideo-sa-video-type';
import type { SAVideoSAVideoName } from './savideo-sa-video-name';
import type { SAVideoSAVideoKind } from './savideo-sa-video-kind';
import type { SANode } from './sanode';
import type { SAVideoSAVideoPosition } from './savideo-sa-video-position';
import type { SAVideoSAVideoNormal } from './savideo-sa-video-normal';
import type { SAVideoSAVideoFlipped } from './savideo-sa-video-flipped';
import type { SAVideoSAVideoSelected } from './savideo-sa-video-selected';

export interface SAVideoSAVideo {
  $type: SAVideoSAVideoType;
  media?: string;
  id: string;
  name?: SAVideoSAVideoName;
  kind?: SAVideoSAVideoKind;
  listItem?: SANode[];
  position?: SAVideoSAVideoPosition;
  normal?: SAVideoSAVideoNormal;
  flipped?: SAVideoSAVideoFlipped;
  selected?: SAVideoSAVideoSelected;
}
